def eval_license(INPUT):
    bb = INPUT[0] + 7
    bc = bb % 26
    bd = bc + 11
    be = int(bd == INPUT[1])
    bf = int(be == 0)
    bg = 25 * bf
    bh = bg + 1
    bj = bb * bh
    bk = INPUT[1] + 15
    bl = bk * bf
    bm = bj + bl
    bn = bm % 26
    bo = bn + 12
    bp = int(bo == INPUT[2])
    bq = int(bp == 0)
    br = 25 * bq
    bt = br + 1
    bu = bm * bt
    bv = INPUT[2] + 2
    bw = bv * bq
    bx = bu + bw
    by = bx % 26
    bz = bx // 26
    cb = by + -3
    cc = int(cb == INPUT[3])
    cd = int(cc == 0)
    ce = 25 * cd
    cf = ce + 1
    cg = bz * cf
    ch = INPUT[3] + 15
    cj = ch * cd
    ck = cg + cj
    cl = ck % 26
    cm = cl + 10
    cn = int(cm == INPUT[4])
    co = int(cn == 0)
    cp = 25 * co
    cq = cp + 1
    cr = ck * cq
    ct = INPUT[4] + 14
    cu = ct * co
    cv = cr + cu
    cw = cv % 26
    cx = cv // 26
    cy = cw + -9
    cz = int(cy == INPUT[5])
    db = int(cz == 0)
    dc = 25 * db
    dd = dc + 1
    de = cx * dd
    df = INPUT[5] + 2
    dg = df * db
    dh = de + dg
    dj = dh % 26
    dk = dj + 10
    dl = int(dk == INPUT[6])
    dm = int(dl == 0)
    dn = 25 * dm
    do = dn + 1
    dp = dh * do
    dq = INPUT[6] + 15
    dr = dq * dm
    dt = dp + dr
    du = dt % 26
    dv = dt // 26
    dw = du + -7
    dx = int(dw == INPUT[7])
    dy = int(dx == 0)
    dz = 25 * dy
    eb = dz + 1
    ec = dv * eb
    ed = INPUT[7] + 1
    ee = ed * dy
    ef = ec + ee
    eg = ef % 26
    eh = ef // 26
    ej = eg + -11
    ek = int(ej == INPUT[8])
    el = int(ek == 0)
    em = 25 * el
    en = em + 1
    eo = eh * en
    ep = INPUT[8] + 15
    eq = ep * el
    er = eo + eq
    et = er % 26
    eu = er // 26
    ev = et + -4
    ew = int(ev == INPUT[9])
    ex = int(ew == 0)
    ey = 25 * ex
    ez = ey + 1
    fb = eu * ez
    fc = INPUT[9] + 15
    fd = fc * ex
    fe = fb + fd
    ff = fe % 26
    fg = ff + 14
    fh = int(fg == INPUT[10])
    fj = int(fh == 0)
    fk = 25 * fj
    fl = fk + 1
    fm = fe * fl
    fn = INPUT[10] + 12
    fo = fn * fj
    fp = fm + fo
    fq = fp % 26
    fr = fq + 11
    ft = int(fr == INPUT[11])
    fu = int(ft == 0)
    fv = 25 * fu
    fw = fv + 1
    fx = fp * fw
    fy = INPUT[11] + 2
    fz = fy * fu
    gb = fx + fz
    gc = gb % 26
    gd = gb // 26
    ge = gc + -8
    gf = int(ge == INPUT[12])
    gg = int(gf == 0)
    gh = 25 * gg
    gj = gh + 1
    gk = gd * gj
    gl = INPUT[12] + 13
    gm = gl * gg
    gn = gk + gm
    go = gn % 26
    gp = gn // 26
    gq = go + -10
    gr = int(gq == INPUT[13])
    gt = int(gr == 0)
    gu = 25 * gt
    gv = gu + 1
    gw = gp * gv
    gx = INPUT[13] + 13
    gy = gx * gt
    gz = gw + gy
    z = gz
    return z == 0
